// =============================================================================
// lib/engine.ts — Sprint runner engine for MindForge
// =============================================================================
// WHAT: Manages the lifecycle of a single sprint — creation, answer recording,
//   completion detection, and summary generation. A sprint is a sequence of
//   5-7 questions answered in rapid succession.
// ROLE: Pure logic layer. Sprints are immutable — recordAnswer returns a new
//   Sprint object rather than mutating. This makes state management predictable
//   and supports React's rendering model.
// DEPENDENCIES:
//   - lib/types.ts (Question, QuestionResult)
// DEPENDENTS:
//   - app/session/session-view.tsx (creates sprints, records answers, checks completion)
//   - app/session/sprint-view.tsx (reads current question from sprint)
//   - app/session/sprint-complete.tsx (displays sprint summary)
//   - __tests__/engine.test.ts
// KEY INVARIANT: Sprint.currentIndex always equals Sprint.results.length.
//   They advance together — each recorded answer bumps both by 1.
// =============================================================================

import type { Question, QuestionResult } from './types'

// Represents an in-progress sprint. Immutable — use recordAnswer() to advance.
// - questions: fixed array of 5-7 questions generated at sprint creation
// - results: grows by 1 with each answer; results[i] is the answer to questions[i]
// - currentIndex: which question to show next (0-based). When currentIndex >= questions.length,
//   the sprint is complete.
export type Sprint = {
  questions: Question[]
  results: QuestionResult[]
  currentIndex: number
}

// Summary statistics for a completed sprint, displayed on the sprint-complete screen.
// - accuracy: 0.0 to 1.0 (correctCount / questionCount)
// - avgResponseTimeMs: rounded average milliseconds per question
export type SprintSummary = {
  questionCount: number
  correctCount: number
  accuracy: number
  avgResponseTimeMs: number
}

// Create a new sprint from a pre-generated array of questions.
// Questions are generated by the game plugin's generateQuestion() function,
// called N times where N = generateSprintQuestionCount() (5-7 questions).
// Starts at index 0 with no results.
export function createSprint(questions: Question[]): Sprint {
  return { questions, results: [], currentIndex: 0 }
}

// Record a player's answer to the current question and advance to the next.
// Returns a NEW Sprint object (immutable pattern — original is not mutated).
// - userAnswer is trimmed before comparison
// - Correctness is a strict equality check: trimmedAnswer === question.answer
// - responseTimeMs is wall-clock time measured by the UI component
// The caller (session-view.tsx) should check isSprintComplete() after this.
export function recordAnswer(sprint: Sprint, userAnswer: string, responseTimeMs: number): Sprint {
  // Get the current question based on index
  const question = sprint.questions[sprint.currentIndex]
  // Trim whitespace from user input before comparing
  const trimmedAnswer = userAnswer.trim()
  // Strict string equality — no fuzzy matching, no case-insensitivity
  const correct = trimmedAnswer === question.answer
  const result: QuestionResult = { question, userAnswer: trimmedAnswer, correct, responseTimeMs }
  // Return a new Sprint with the result appended and index advanced by 1
  return { ...sprint, results: [...sprint.results, result], currentIndex: sprint.currentIndex + 1 }
}

// Check if all questions in the sprint have been answered.
// True when currentIndex has reached or passed the end of the questions array.
export function isSprintComplete(sprint: Sprint): boolean {
  return sprint.currentIndex >= sprint.questions.length
}

// Compute summary statistics for a completed (or in-progress) sprint.
// Used by the sprint-complete screen (app/session/sprint-complete.tsx) and
// by session-view.tsx to feed into Elo calculation and difficulty adjustment.
// Edge case: if no results yet, accuracy and avgResponseTimeMs are both 0.
export function getSprintSummary(sprint: Sprint): SprintSummary {
  const correctCount = sprint.results.filter(r => r.correct).length
  const totalTime = sprint.results.reduce((sum, r) => sum + r.responseTimeMs, 0)
  return {
    questionCount: sprint.results.length,
    correctCount,
    // Avoid division by zero when no results exist
    accuracy: sprint.results.length > 0 ? correctCount / sprint.results.length : 0,
    avgResponseTimeMs: sprint.results.length > 0 ? Math.round(totalTime / sprint.results.length) : 0,
  }
}

// Generate a random question count for a sprint: 5, 6, or 7.
// The randomness keeps sprints unpredictable in length, preventing players
// from "counting down" and changing their behavior on the last question.
// Math.floor(Math.random() * 3) produces 0, 1, or 2 → plus 5 → 5, 6, or 7.
export function generateSprintQuestionCount(): number {
  return Math.floor(Math.random() * 3) + 5
}
